### ISSUE TITLE
`dbClient.transaction` restriction

### ISSUE THREAD

**Issue by NPCRUS** [com-lihaoyi/scalasql#51]
I'm migrating my current side project to scalasql and I'm quite confused by the fact, that even simple select queries I need to wrap inside `dbClient.transaction` block. I looked into the `DbClient` and `DbApi` and I don't see any reason why all the db access methods like `run` cannot be exposed wrapped in such way:
```scala
def run[Q, R](query: Q, fetchSize: Int = -1, queryTimeoutSeconds: Int = -1)(
      implicit qr: Queryable[Q, R],
      fileName: sourcecode.FileName,
      lineNum: sourcecode.Line
  ): R = {
    val connection = getAutoCommitClientConnection
    try  connection.run(query, fetchSize, queryTimeoutSeconds)
    finally connection.close()
  }
```
(obviously final code will be different and both layers will need to be slightly redesigned)

So I have two questions:
1) Is there something I don't see that forces such api design?
2) If not, what would be the process towards changes in api?
I am also willing to work on this if there's green light

**Comment by aboisvert** [comment]
I think the design is oriented towards business apps that have a combination of reads/writes, where it's desirable to have transactions, isolation level, consistency across read statements, etc. by default.

It's certainly been like the right default for the apps I've written using Scalasql (and I'm pretty sure we have the biggest app using Scalasql at this point).

That being said, there have been a few times where I've reached for an auto-commit client connection, and I'd welcome having another API that wrap operations in a try/finally/close.    

I'll also note that some operations, like `stream` will need a bit of rethink with auto-commit since all the streaming needs to happen with the connection open, so would require some sort of callback function passed into the operation.

**Comment by lihaoyi** [comment]
I think having a wrapper is certainly possible. Exactly what it would look like is to be determined, but feel free to try and come up with something and open a PR to discuss

**Comment by NPCRUS** [comment]
> It's not quite clear to me what your proposal adds that direct usage of `getAutocommitClientConnection` lacks. Is it the try-finally around every command?

@lihaoyi yes, this is exactly the annoying part, if you repeat it more than 10 times, there is slight chance in one of those you'll forget to `close` the connection

**Comment by lihaoyi** [comment]
Got it. Yes as @aboisvert mentioned, in most cases I've ever used a database it's been with a persistent connection and long-lived transaction, both for connection re-use (since connections are expensive and scarce) as well as for transaction management (e.g. to commit or rollback multiple statements atomically). 

Your statement `even simple select queries I need to wrap inside dbClient.transaction block.` makes me a bit curious, because the nature of databases is that `SELECT`s benefit from being in transactions as much as any `INSERT` or `UPDATE` clause, and those transactions need to be managed appropriately

If you want to add your own wrapper to create short-lived connections/transactions per command, you can go ahead and do so.  `trait DbApi` is intentionally a pure interface so you can feel free to write your own implementations or wrappers
